#!/bin/bash
echo "==== complete install QO100 Transceiver ===="
echo "full update, upgrade and installation"
set -e
cd ~
echo "update system by running apt-get update"
sudo apt-get update
echo "install git"
sudo apt-get install git -y
if [ ! -d "QO100_Transceiver_OH1VX" ] ; then
        git clone https://github.com/OH1VX/QO100_Transceiver QO100_Transceiver_OH1VX
        cd QO100_Transceiver_OH1VX
    else
        cd QO100_Transceiver_OH1VX
        git pull https://github.com/OH1VX/QO100_Transceiver QO100_Transceiver_OH1VX
    fi
cd ~/QO100_Transceiver_OH1VX/scripts
./prepare_ubuntu_pluto
cd ~/QO100_Transceiver_OH1VX/scripts
./makeall
echo "==== Installation: OK ===="
cd ~/QO100_Transceiver_OH1VX/Release
echo "==== Start the Transceiver in the folder QO100_Transceiver_OH1VX/Release ===="
echo "==== by entering ./startQO100trx                                   ===="
